#!/usr/bin/env python3
"""
Investigate what payment allocations the CSP is generating
"""
from core.models import Loan
from core.solver import ConstraintSolver
from copy import deepcopy

loans = [
    Loan("CC", 5000, 18.0, 150),
    Loan("Car", 15000, 6.5, 350),
    Loan("Student", 20000, 4.5, 200),
]

# Month 0 scenario
budget = 1000
emergency_floor = 500
current_cash = 2000

print("=" * 70)
print("CSP ALLOCATION ANALYSIS - Month 0")
print("=" * 70)

print(f"\nConstraints:")
print(f"  Budget: ${budget}/month")
print(f"  Cash available: ${current_cash}")
print(f"  Emergency floor: ${emergency_floor}")
print(f"  Min payments: CC ${loans[0].min_payment} + Car ${loans[1].min_payment} + Student ${loans[2].min_payment} = ${700}")
print(f"  Extra available: ${budget - 700}")

solver = ConstraintSolver(deepcopy(loans), budget, emergency_floor, current_cash, granularity=100)

# Check domain setup
solver.setup_domains()
print(f"\nDomains generated by CSP:")
for loan_name, options in solver.domains.items():
    print(f"  {loan_name}: {options}")

# Get all valid allocations
allocations = solver.get_valid_allocations()
print(f"\nTotal valid allocations generated: {len(allocations)}")

# Sort by total payment
allocations.sort(key=lambda a: sum(a.values()))

print(f"\nFirst 20 allocations (sorted by total payment):")
for i, alloc in enumerate(allocations[:20]):
    total = sum(alloc.values())
    print(f"  {i+1:2}. CC=${alloc['CC']:>6.0f}  Car=${alloc['Car']:>6.0f}  Student=${alloc['Student']:>6.0f}  Total=${total:>6.0f}")

# Check if the Snowball allocation ($450, $350, $200) is in the list
snowball_alloc = {'CC': 450, 'Car': 350, 'Student': 200}
if snowball_alloc in allocations:
    print(f"\n✓ Snowball allocation {snowball_alloc} IS in the valid set")
else:
    print(f"\n✗ Snowball allocation {snowball_alloc} IS NOT in the valid set!")
    print("   This explains why A* can't find the Snowball solution!")

# Check different CC allocations
print(f"\nCC payment options generated by CSP:")
cc_options = sorted(set(a['CC'] for a in allocations))
print(f"  {cc_options}")

snowball_cc_payment = 450
if snowball_cc_payment in cc_options:
    print(f"\n✓ CC payment of ${snowball_cc_payment} is allowed by CSP")
else:
    print(f"\n✗ CC payment of ${snowball_cc_payment} is NOT allowed by CSP!")
